### ISSUE TITLE
Why didn't you use node

### ISSUE THREAD

**Issue by turtle0x1** [nekobit1/starchat#13]
If you want to make a chat app why did you choose PHP over node ? Node is far better equipped for this kind of application

**Comment by emilengler** [comment]
I'm also the opinion that node is a better choice than php for a chat. Node is perfect for live applications like chats.

**Comment by saderror256** [comment]
Yes I know but I have already dug in too much, I cannot just take months worth of code and scrap it for Node now

**Comment by nekobit1** [comment]
Node project may come soon. Stay tuned :)
