### ISSUE TITLE
Return Less Messages

### ISSUE THREAD

**Issue by nekobit1** [nekobit1/starchat#24]
So basically I will put context here, say someone was to have a conversation with over 1000 messages, that would be terrible to constantly load messages, this can kill bandwidth

If you scroll up a bit more (referring to client side), it would get even more messages, we would call it like this

>/api/v1/?username=*XXXXXX*&password=*XXXXXX*&contact=*XXXXXX*&getmessages=25

Would return 25 messages. Or you can pass `getmessages=all`

And yes as you can tell, all this work is done server, obviously...

Also, to clean up the api, we will add some tree functions like if the user adds the contact get variable, this would allow you to use other get requests cleanly, instead of rewriting features over and over again in the api.

Please tell me your opinion and add any suggestions if you want to use an emoji reaction! Thanks!

**Comment by turtle0x1** [comment]
This is a good idea, when the user scrolls to the top of the messages more should load!

**Comment by nekobit1** [comment]
Complete! Sorry, took a break from the project for a bit.
