### ISSUE TITLE
Move html from php controllers to models

### ISSUE THREAD

**Issue by KaeseKuchenDEV** [nekobit1/starchat#33]
I would say that everything that has to do with html in the php files should be moved in models so the controllers are more readable and shorter. So the controllers have to include the models.

**Comment by nekobit1** [comment]
Good idea, I need to get websocket support working first, see the websocket branch :)

**Comment by KaeseKuchenDEV** [comment]
I could do this. This would be a good introduction into your code so i could help you with the websockets

**Comment by nekobit1** [comment]
Yeah, the code is actually a little bit messy, I started this with a bit of PHP experience and as I moved on, this project is still alive and kicking somehow

**Comment by nekobit1** [comment]
@KaeseKuchenDEV Sorry for ignoring your request for so long. I am actually going to rewrite starchat in Node.js so this project will be archived/deleted someday.
